name: paydeuk-web CI/CD Pipeline

on:
  push:
    branches:
      - dev
 
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # 최신 커밋 전체 히스토리 보장

      - name: Debug - check commit and page.tsx content
        run: |
          git log -1
          echo "--- page.tsx ---"
          cat app/page.tsx || echo "파일 없음"

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.12.0

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: DockerHub Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Docker Build & Push
        run: |
          docker build --no-cache -t ${{ secrets.DOCKER_HUB_USERNAME }}/paydeuk_server_web .
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/paydeuk_server_web

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "[EC2] Pulling latest image and restarting container..."
            docker rm -f paydeuk_server_web || true
            docker rmi ${{ secrets.DOCKER_HUB_USERNAME }}/paydeuk_server_web || true
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/paydeuk_server_web
            docker run -d --name paydeuk_server_web -p 3000:3000 ${{ secrets.DOCKER_HUB_USERNAME }}/paydeuk_server_web
